name: flutter_markdown
author: Flutter Authors <flutter-dev@googlegroups.com>
description: A Markdown renderer for Flutter.
homepage: https://github.com/flutter/flutter_markdown
version: 0.6.14
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"


dependencies:
  flutter: 
    sdk: flutter
  markdown:
    git: https://github.com/logneh4/markdown.git
    
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.3.2
  standard_message_codec: ^0.0.1+3